version: "3.9"
services:
  backend:
    build: ./backend
    container_name: 5cnp-backend
    ports: ["8000:8000"]
  frontend:
    build: ./frontend
    container_name: 5cnp-frontend
    ports: ["5173:80"]
    depends_on: ["backend"]
